baseURL = "http://unused.github.io/blog/"
languageCode = "en-us"
title = "unused Blog on GitHub"
theme = "minimo"

[params]
  description = "Posts about Linux, (web) development, and other stuff."
  dateFormat = "2017, Aug 6"

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[author]
  name = "Christoph Lipautz"

[permalinks]
  page = "/:slug/"

# Language Configuration
defaultContentLanguage = "en"
