baseURL = "http://unused.github.io/blog/"
languageCode = "en-us"
title = "unused Blog on GitHub"
theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 4200

preserveTaxonomyNames = true

[params]
  description = "Posts about Linux, (web) development, and other stuff."
  dateFormat = "2017, Aug 6"
  copyright = "©2017 Christoph Lipautz, any code snippet is free to use, licensed under cc by-sa 3.0"
  favicon = "favicon.ico"
  hideEntryNavigation = true
  customCSS = []
  customJS = []
  hideSocialMenu = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Christoph Lipautz"

[author.social]
  codepen = ""
  facebook = ""
  github = "unused"
  instagram = ""
  twitter = "lipdaguit"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Edit on GitHub"
  weight = 0
  identifier = "repository"
  url = "https://github.com/unused/blog"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
